git:
  paging:
    colorArg: always
    pager: delta --paging=never
  pull:
    mode: "rebase"

gui:
  showCommandLog: false
  showFileTree: true
  skipstashwarning: true
  skipunstagelinewarning: false
  theme:
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - "#CFC1BA"

startuppopupversion: 1
notARepository: "skip"
keybinding:
  files:
    commitChanges: "C"
    commitChangesWithEditor: "c"
    toggleTreeView: "t"
  commits:
    renameCommit: "R"
    renameCommitWithEditor: "r"
