[settings]
trusted_config_paths = ['$HOME/Code']

[tools]
actionlint = "latest"
checkmake = "latest"
dotenv-linter = "latest"
hadolint = "latest"
lua-language-server = "latest"
marksman = "latest"
node = "lts"
pnpm = "latest"
pre-commit = "latest"
python = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
terraform-ls = "latest"
uv = "latest"
